-- Create direct_messages table
CREATE TABLE IF NOT EXISTS direct_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sender_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    receiver_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    message TEXT NOT NULL,
    sent_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    read_at TIMESTAMP WITH TIME ZONE
);

-- Indexes for performance
CREATE INDEX IF NOT EXISTS direct_messages_sender_id_idx ON direct_messages(sender_id);
CREATE INDEX IF NOT EXISTS direct_messages_receiver_id_idx ON direct_messages(receiver_id);

-- RLS Policies
ALTER TABLE direct_messages ENABLE ROW LEVEL SECURITY;

-- Policy: Users can see messages they sent or received
CREATE POLICY "Users can view their own direct messages" 
ON direct_messages FOR SELECT 
USING (auth.uid() = sender_id OR auth.uid() = receiver_id);

-- Policy: Users can insert messages (as sender)
CREATE POLICY "Users can send direct messages" 
ON direct_messages FOR INSERT 
WITH CHECK (auth.uid() = sender_id);

-- Policy: Users can update messages they received (e.g. marking as read)
CREATE POLICY "Users can update received direct messages" 
ON direct_messages FOR UPDATE 
USING (auth.uid() = receiver_id);
