-- Create friendships table
CREATE TABLE IF NOT EXISTS friendships (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    requester_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    receiver_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    status TEXT NOT NULL CHECK (status IN ('pending', 'accepted')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    UNIQUE(requester_id, receiver_id)
);

-- Indexes for performance
CREATE INDEX IF NOT EXISTS friendships_requester_id_idx ON friendships(requester_id);
CREATE INDEX IF NOT EXISTS friendships_receiver_id_idx ON friendships(receiver_id);
CREATE INDEX IF NOT EXISTS friendships_status_idx ON friendships(status);

-- RLS Policies
ALTER TABLE friendships ENABLE ROW LEVEL SECURITY;

-- Policy: Users can see their own friendships (either as requester or receiver)
CREATE POLICY "Users can view their own friendships" 
ON friendships FOR SELECT 
USING (auth.uid() = requester_id OR auth.uid() = receiver_id);

-- Policy: Users can insert friend requests (as requester)
CREATE POLICY "Users can create friend requests" 
ON friendships FOR INSERT 
WITH CHECK (auth.uid() = requester_id);

-- Policy: Users can update their own friendships (e.g. accepting a request)
CREATE POLICY "Users can update their own friendships" 
ON friendships FOR UPDATE 
USING (auth.uid() = requester_id OR auth.uid() = receiver_id);

-- Policy: Users can delete their own friendships
CREATE POLICY "Users can delete their own friendships" 
ON friendships FOR DELETE 
USING (auth.uid() = requester_id OR auth.uid() = receiver_id);

-- Function to update updated_at
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ language 'plpgsql';

CREATE TRIGGER update_friendships_updated_at
    BEFORE UPDATE ON friendships
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();
