-- ========================================
-- FUTMATCH - MIGRAÃ‡ÃƒO COMPLETA DO BANCO DE DADOS
-- ========================================
-- Execute este arquivo no Supabase SQL Editor
-- ContÃ©m todas as tabelas, funÃ§Ãµes e polÃ­ticas RLS
-- ========================================


-- ========================================
-- 1. CRIAR TABELA DE PERFLS (profiles)
-- ========================================

CREATE TABLE IF NOT EXISTS public.profiles (
  id uuid references auth.users on delete cascade not null primary key,
  name text,
  photo_url text,
  date_of_birth text,
  city text,
  state text,
  sport text[],
  "position" text[],
  bio text,
  points integer default 0 not null,
  matches_played integer default 0 not null,
  reputation text default 'Iniciante'::text not null,
  banner_url text,
  favorite_team text,
  favorite_team_logo_url text,
  updated_at timestamp with time zone,
  available_roles text[] DEFAULT '{}',
  coach_specialties text[] DEFAULT '{}',
  referred_by uuid REFERENCES auth.users(id),
  signup_bonus_claimed boolean DEFAULT false
);

-- Habilitar RLS
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

-- PolÃ­ticas RLS (DROPIfExists para evitar erro)
DROP POLICY IF EXISTS "Public profiles are viewable by everyone." ON public.profiles;
CREATE POLICY "Public profiles are viewable by everyone." 
ON public.profiles FOR SELECT USING (true);

DROP POLICY IF EXISTS "Users can insert their own profile." ON public.profiles;
CREATE POLICY "Users can insert their own profile." 
ON public.profiles FOR INSERT WITH CHECK (auth.uid() = id);

DROP POLICY IF EXISTS "Users can update their own profile." ON public.profiles;
CREATE POLICY "Users can update their own profile." 
ON public.profiles FOR UPDATE USING (auth.uid() = id);


-- ========================================
-- 2. CRIAR TABELA DE TOKENS (tokens)
-- ========================================

CREATE TABLE IF NOT EXISTS public.tokens (
  user_id uuid REFERENCES public.profiles ON DELETE CASCADE NOT NULL PRIMARY KEY,
  balance integer DEFAULT 10 NOT NULL,
  updated_at timestamp with time zone DEFAULT now()
);

-- Habilitar RLS
ALTER TABLE public.tokens ENABLE ROW LEVEL SECURITY;

-- PolÃ­ticas RLS
DROP POLICY IF EXISTS "Users can view their own tokens." ON public.tokens;
CREATE POLICY "Users can view their own tokens." 
ON public.tokens FOR SELECT USING (auth.uid() = user_id);


-- ========================================
-- 3. CRIAR TABELA DE PARTIDAS (matches)
-- ========================================

CREATE TABLE IF NOT EXISTS public.matches (
  id bigint generated by default as identity primary key,
  created_by uuid references auth.users not null,
  name text not null,
  sport text not null,
  location text not null,
  lat real null,
  lng real null,
  date timestamp with time zone not null,
  slots integer not null,
  filled_slots integer default 0 not null,
  rules text,
  status text default 'Convocando'::text not null,
  cancellation_reason text,
  is_boosted boolean default false,
  boost_score integer DEFAULT 0,
  boost_until timestamp with time zone,
  is_private boolean default false,
  invite_code text,
  team_id BIGINT,
  created_at timestamp with time zone default now() not null
);

-- Habilitar RLS
ALTER TABLE public.matches ENABLE ROW LEVEL SECURITY;

-- PolÃ­ticas RLS
DROP POLICY IF EXISTS "Matches are viewable by everyone." ON public.matches;
CREATE POLICY "Matches are viewable by everyone." 
ON public.matches FOR SELECT USING (true);

DROP POLICY IF EXISTS "Authenticated users can create matches." ON public.matches;
CREATE POLICY "Authenticated users can create matches." 
ON public.matches FOR INSERT WITH CHECK (auth.role() = 'authenticated');

DROP POLICY IF EXISTS "Users can update their own matches." ON public.matches;
CREATE POLICY "Users can update their own matches." 
ON public.matches FOR UPDATE USING (auth.uid() = created_by);

DROP POLICY IF EXISTS "Users can delete their own matches." ON public.matches;
CREATE POLICY "Users can delete their own matches." 
ON public.matches FOR DELETE USING (auth.uid() = created_by);

-- Ãndices para performance
CREATE INDEX IF NOT EXISTS idx_matches_boost ON public.matches (boost_score DESC, boost_until DESC);
CREATE INDEX IF NOT EXISTS idx_matches_invite_code ON public.matches (invite_code) WHERE invite_code IS NOT NULL;


-- ========================================
-- 4. CRIAR TABELA DE PARTICIPANTES (match_participants)
-- ========================================

CREATE TABLE IF NOT EXISTS public.match_participants (
  match_id bigint REFERENCES public.matches ON DELETE CASCADE NOT NULL,
  user_id uuid REFERENCES public.profiles ON DELETE CASCADE NOT NULL,
  status text DEFAULT 'confirmed',
  joined_at timestamp with time zone DEFAULT now() NOT NULL,
  waitlist_position int,
  PRIMARY KEY (match_id, user_id)
);

-- Habilitar RLS
ALTER TABLE public.match_participants ENABLE ROW LEVEL SECURITY;

-- PolÃ­ticas RLS
DROP POLICY IF EXISTS "Participants are viewable by everyone." ON public.match_participants;
CREATE POLICY "Participants are viewable by everyone." 
ON public.match_participants FOR SELECT USING (true);

DROP POLICY IF EXISTS "Users can join a match." ON public.match_participants;
CREATE POLICY "Users can join a match." 
ON public.match_participants FOR INSERT WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can leave their own match." ON public.match_participants;
CREATE POLICY "Users can leave their own match." 
ON public.match_participants FOR DELETE USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can update their own participation." ON public.match_participants;
CREATE POLICY "Users can update their own participation." 
ON public.match_participants FOR UPDATE USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);


-- ========================================
-- 5. CRIAR TABELA DE TIMES (teams)
-- ========================================

CREATE TABLE IF NOT EXISTS public.teams (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_by UUID NOT NULL REFERENCES auth.users(id),
    name TEXT NOT NULL,
    description TEXT,
    logo_url TEXT,
    invite_code TEXT UNIQUE DEFAULT encode(gen_random_bytes(6), 'hex'),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Habilitar RLS
ALTER TABLE public.teams ENABLE ROW LEVEL SECURITY;

-- PolÃ­ticas RLS
DROP POLICY IF EXISTS "Times sÃ£o visÃ­veis para todos" ON public.teams;
CREATE POLICY "Times sÃ£o visÃ­veis para todos" ON public.teams
    FOR SELECT USING (true);

DROP POLICY IF EXISTS "UsuÃ¡rios autenticados podem criar times" ON public.teams;
CREATE POLICY "UsuÃ¡rios autenticados podem criar times" ON public.teams
    FOR INSERT WITH CHECK (auth.uid() = created_by);

DROP POLICY IF EXISTS "Apenas criador pode editar time" ON public.teams;
CREATE POLICY "Apenas criador pode editar time" ON public.teams
    FOR UPDATE USING (auth.uid() = created_by);

DROP POLICY IF EXISTS "Apenas criador pode deletar time" ON public.teams;
CREATE POLICY "Apenas criador pode deletar time" ON public.teams
    FOR DELETE USING (auth.uid() = created_by);


-- ========================================
-- 6. CRIAR TABELA DE MEMBROS DO TIME (team_members)
-- ========================================

CREATE TABLE IF NOT EXISTS public.team_members (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    team_id BIGINT NOT NULL REFERENCES public.teams(id) ON DELETE CASCADE,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    status TEXT NOT NULL CHECK (status IN ('pending', 'approved', 'rejected')),
    role TEXT NOT NULL DEFAULT 'member' CHECK (role IN ('admin', 'member')),
    joined_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    UNIQUE(team_id, user_id)
);

-- Habilitar RLS
ALTER TABLE public.team_members ENABLE ROW LEVEL SECURITY;

-- PolÃ­ticas RLS
DROP POLICY IF EXISTS "Membros de time sÃ£o visÃ­veis para todos" ON public.team_members;
CREATE POLICY "Membros de time sÃ£o visÃ­veis para todos" ON public.team_members
    FOR SELECT USING (true);

DROP POLICY IF EXISTS "UsuÃ¡rios podem solicitar entrada" ON public.team_members;
CREATE POLICY "UsuÃ¡rios podem solicitar entrada" ON public.team_members
    FOR INSERT WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Admins podem atualizar membros" ON public.team_members;
CREATE POLICY "Admins podem atualizar membros" ON public.team_members
    FOR UPDATE USING (
        EXISTS (
            SELECT 1 FROM public.teams
            WHERE id = team_members.team_id AND created_by = auth.uid()
        )
        OR
        EXISTS (
            SELECT 1 FROM public.team_members AS tm
            WHERE tm.team_id = team_members.team_id
            AND tm.user_id = auth.uid()
            AND tm.role = 'admin'
            AND tm.status = 'approved'
        )
    );

DROP POLICY IF EXISTS "Admins removem ou usuario sai" ON public.team_members;
CREATE POLICY "Admins removem ou usuario sai" ON public.team_members
    FOR DELETE USING (
        user_id = auth.uid()
        OR
        EXISTS (
            SELECT 1 FROM public.teams
            WHERE id = team_members.team_id AND created_by = auth.uid()
        )
        OR
        EXISTS (
            SELECT 1 FROM public.team_members AS tm
            WHERE tm.team_id = team_members.team_id
            AND tm.user_id = auth.uid()
            AND tm.role = 'admin'
            AND tm.status = 'approved'
        )
    );


-- ========================================
-- 7. CRIAR TABELA DE MENSAGENS DE PARTIDA (match_messages)
-- ========================================

CREATE TABLE IF NOT EXISTS public.match_messages (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  match_id bigint REFERENCES public.matches ON DELETE CASCADE NOT NULL,
  sender_id uuid REFERENCES public.profiles ON DELETE SET NULL NOT NULL,
  message text NOT NULL,
  sent_at timestamp with time zone DEFAULT now()
);

-- Habilitar RLS
ALTER TABLE public.match_messages ENABLE ROW LEVEL SECURITY;

-- PolÃ­ticas RLS
DROP POLICY IF EXISTS "Participants can view messages" ON public.match_messages;
CREATE POLICY "Participants can view messages" ON public.match_messages FOR SELECT USING (
  EXISTS (
    SELECT 1 FROM public.match_participants mp 
    WHERE mp.match_id = match_messages.match_id AND mp.user_id = auth.uid()
  )
  OR
  EXISTS (
    SELECT 1 FROM public.matches m 
    WHERE m.id = match_messages.match_id AND m.created_by = auth.uid()
  )
);

DROP POLICY IF EXISTS "Participants can send messages" ON public.match_messages;
CREATE POLICY "Participants can send messages" ON public.match_messages FOR INSERT WITH CHECK (
  (auth.uid() = sender_id) AND (
    EXISTS (
        SELECT 1 FROM public.match_participants mp 
        WHERE mp.match_id = match_messages.match_id AND mp.user_id = auth.uid()
    )
    OR
    EXISTS (
        SELECT 1 FROM public.matches m 
        WHERE m.id = match_messages.match_id AND m.created_by = auth.uid()
    )
  )
);


-- ========================================
-- 8. CRIAR TABELA DE MENSAGENS DIRETAS (direct_messages)
-- ========================================

CREATE TABLE IF NOT EXISTS public.direct_messages (
  id bigint generated by default as identity primary key,
  sender_id uuid REFERENCES auth.users NOT NULL,
  receiver_id uuid REFERENCES auth.users NOT NULL,
  message text NOT NULL,
  sent_at timestamp with time zone DEFAULT now() NOT NULL,
  read_at timestamp with time zone
);

-- Habilitar RLS
ALTER TABLE public.direct_messages ENABLE ROW LEVEL SECURITY;

-- PolÃ­ticas RLS
DROP POLICY IF EXISTS "Users can see messages they sent or received." ON public.direct_messages;
CREATE POLICY "Users can see messages they sent or received." 
ON public.direct_messages FOR SELECT USING (auth.uid() = sender_id OR auth.uid() = receiver_id);

DROP POLICY IF EXISTS "Users can send direct messages." ON public.direct_messages;
CREATE POLICY "Users can send direct messages." 
ON public.direct_messages FOR INSERT WITH CHECK (auth.uid() = sender_id);

DROP POLICY IF EXISTS "Users can update received direct messages." ON public.direct_messages;
CREATE POLICY "Users can update received direct messages." 
ON public.direct_messages FOR UPDATE USING (auth.uid() = receiver_id);

-- Ãndices para performance
CREATE INDEX IF NOT EXISTS direct_messages_sender_id_idx ON public.direct_messages(sender_id);
CREATE INDEX IF NOT EXISTS direct_messages_receiver_id_idx ON public.direct_messages(receiver_id);


-- ========================================
-- 9. CRIAR TABELA DE POSTS DA COMUNIDADE (community_posts)
-- ========================================

CREATE TABLE IF NOT EXISTS public.community_posts (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id uuid REFERENCES public.profiles ON DELETE CASCADE NOT NULL,
  content text NOT NULL,
  image_url text,
  likes_count integer DEFAULT 0,
  comments_count integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now()
);

-- Habilitar RLS
ALTER TABLE public.community_posts ENABLE ROW LEVEL SECURITY;

-- PolÃ­ticas RLS
DROP POLICY IF EXISTS "Posts are viewable by everyone." ON public.community_posts;
CREATE POLICY "Posts are viewable by everyone." 
ON public.community_posts FOR SELECT USING (true);

DROP POLICY IF EXISTS "Authenticated users can insert posts." ON public.community_posts;
CREATE POLICY "Authenticated users can insert posts." 
ON public.community_posts FOR INSERT WITH CHECK (auth.role() = 'authenticated');

DROP POLICY IF EXISTS "Users can update their own posts." ON public.community_posts;
CREATE POLICY "Users can update their own posts." 
ON public.community_posts FOR UPDATE USING (auth.uid() = user_id);


-- ========================================
-- 10. CRIAR TABELA DE COMENTÃRIOS (community_comments)
-- ========================================

CREATE TABLE IF NOT EXISTS public.community_comments (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  post_id uuid REFERENCES public.community_posts ON DELETE CASCADE NOT NULL,
  user_id uuid REFERENCES public.profiles ON DELETE CASCADE NOT NULL,
  content text NOT NULL,
  created_at timestamp with time zone DEFAULT now()
);

-- Habilitar RLS
ALTER TABLE public.community_comments ENABLE ROW LEVEL SECURITY;

-- PolÃ­ticas RLS
DROP POLICY IF EXISTS "Comments are viewable by everyone." ON public.community_comments;
CREATE POLICY "Comments are viewable by everyone." 
ON public.community_comments FOR SELECT USING (true);

DROP POLICY IF EXISTS "Authenticated users can insert comments." ON public.community_comments;
CREATE POLICY "Authenticated users can insert comments." 
ON public.community_comments FOR INSERT WITH CHECK (auth.role() = 'authenticated');


-- ========================================
-- 11. CRIAR TABELA DE LIKES (community_likes)
-- ========================================

CREATE TABLE IF NOT EXISTS public.community_likes (
  post_id uuid REFERENCES public.community_posts ON DELETE CASCADE NOT NULL,
  user_id uuid REFERENCES public.profiles ON DELETE CASCADE NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  PRIMARY KEY (post_id, user_id)
);

-- Habilitar RLS
ALTER TABLE public.community_likes ENABLE ROW LEVEL SECURITY;

-- PolÃ­ticas RLS
DROP POLICY IF EXISTS "Likes are viewable by everyone." ON public.community_likes;
CREATE POLICY "Likes are viewable by everyone." 
ON public.community_likes FOR SELECT USING (true);

DROP POLICY IF EXISTS "Authenticated users can like posts." ON public.community_likes;
CREATE POLICY "Authenticated users can like posts." 
ON public.community_likes FOR INSERT WITH CHECK (auth.role() = 'authenticated');

DROP POLICY IF EXISTS "Users can remove their own likes." ON public.community_likes;
CREATE POLICY "Users can remove their own likes." 
ON public.community_likes FOR DELETE USING (auth.uid() = user_id);


-- ========================================
-- 12. CRIAR TABELA DE ARENAS (arenas)
-- ========================================

CREATE TABLE IF NOT EXISTS public.arenas (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  name text NOT NULL,
  city text NOT NULL,
  state text NOT NULL,
  neighborhood text,
  address text,
  location_link text,
  sports text[],
  price_info text,
  phone text,
  whatsapp text,
  is_partner boolean DEFAULT false,
  banner_url text,
  created_at timestamp with time zone DEFAULT now()
);

-- Habilitar RLS
ALTER TABLE public.arenas ENABLE ROW LEVEL SECURITY;

-- PolÃ­ticas RLS
DROP POLICY IF EXISTS "Arenas are viewable by everyone." ON public.arenas;
CREATE POLICY "Arenas are viewable by everyone." 
ON public.arenas FOR SELECT USING (true);

-- Inserir arenas padrÃ£o
INSERT INTO public.arenas (name, city, state, neighborhood, address, sports, price_info, phone, whatsapp, is_partner, banner_url)
VALUES 
('Arena FutMatch Pro', 'Sorocaba', 'SP', 'Campolim', 'Av. Gisele Constantino, 1200', ARRAY['Futebol Society', 'Futsal'], 'R$ 150/hora', '(15) 99999-0000', '5515999990000', true, 'https://images.unsplash.com/photo-1529900748604-07564a03e7a6?q=80&w=2070&auto=format&fit=crop'),
('Quadra do ZÃ©', 'Sorocaba', 'SP', 'Centro', 'Rua da Penha, 500', ARRAY['Futebol Society'], 'R$ 100/hora', '(15) 3333-4444', null, false, 'https://images.unsplash.com/photo-1575361204480-aadea25e6e68?q=80&w=2071&auto=format&fit=crop'),
('Complexo Esportivo VÃ´lei & Cia', 'Itu', 'SP', 'Vila Nova', 'Rua Floriano Peixoto, 10', ARRAY['VÃ´lei de Quadra', 'VÃ´lei de Praia / Areia', 'FutevÃ´lei'], 'R$ 80/hora', '(11) 98888-7777', '5511988887777', true, 'https://images.unsplash.com/photo-1612872087720-bb876e2e67d1?q=80&w=2007&auto=format&fit=crop'),
('Beach Tennis Point', 'Sorocaba', 'SP', 'Santa RosÃ¡lia', 'Av. Dom Aguirre, 2000', ARRAY['Beach Tennis'], 'R$ 120/hora', '(15) 97777-6666', '5515977776666', true, 'https://images.unsplash.com/photo-1632919661367-454109336799?q=80&w=2070&auto=format&fit=crop')
ON CONFLICT (id) DO NOTHING;


-- ========================================
-- 13. CRIAR TABELA DE NOTIFICAÃ‡Ã•ES (notifications)
-- ========================================

CREATE TABLE IF NOT EXISTS public.notifications (
  id bigint generated by default as identity primary key,
  user_id uuid REFERENCES public.profiles ON DELETE CASCADE NOT NULL,
  type text NOT NULL,
  title text NOT NULL,
  body text NOT NULL,
  data jsonb,
  is_read boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now()
);

-- Habilitar RLS
ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;

-- PolÃ­ticas RLS
DROP POLICY IF EXISTS "Users can view own notifications." ON public.notifications;
CREATE POLICY "Users can view own notifications." 
ON public.notifications FOR SELECT USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can update own notifications." ON public.notifications;
CREATE POLICY "Users can update own notifications." 
ON public.notifications FOR UPDATE USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Authenticated users can insert notifications." ON public.notifications;
CREATE POLICY "Authenticated users can insert notifications." 
ON public.notifications FOR INSERT WITH CHECK (auth.role() = 'authenticated');


-- ========================================
-- 14. CRIAR TABELA DE AMIZADES (friendships)
-- ========================================

CREATE TABLE IF NOT EXISTS public.friendships (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    requester_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    receiver_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    status TEXT NOT NULL CHECK (status IN ('pending', 'accepted')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    UNIQUE(requester_id, receiver_id)
);

-- Ãndices para performance
CREATE INDEX IF NOT EXISTS friendships_requester_id_idx ON public.friendships(requester_id);
CREATE INDEX IF NOT EXISTS friendships_receiver_id_idx ON public.friendships(receiver_id);
CREATE INDEX IF NOT EXISTS friendships_status_idx ON public.friendships(status);

-- Habilitar RLS
ALTER TABLE public.friendships ENABLE ROW LEVEL SECURITY;

-- PolÃ­ticas RLS
DROP POLICY IF EXISTS "Users can view their own friendships" ON public.friendships;
CREATE POLICY "Users can view their own friendships" 
ON public.friendships FOR SELECT 
USING (auth.uid() = requester_id OR auth.uid() = receiver_id);

DROP POLICY IF EXISTS "Users can create friend requests" ON public.friendships;
CREATE POLICY "Users can create friend requests" 
ON public.friendships FOR INSERT 
WITH CHECK (auth.uid() = requester_id);

DROP POLICY IF EXISTS "Users can update their own friendships" ON public.friendships;
CREATE POLICY "Users can update their own friendships" 
ON public.friendships FOR UPDATE 
USING (auth.uid() = requester_id OR auth.uid() = receiver_id);

DROP POLICY IF EXISTS "Users can delete their own friendships" ON public.friendships;
CREATE POLICY "Users can delete their own friendships" 
ON public.friendships FOR DELETE 
USING (auth.uid() = requester_id OR auth.uid() = receiver_id);


-- ========================================
-- 15. TRIGGERS E FUNCTIONS
-- ========================================

-- Function para criar perfil automaticamente quando usuÃ¡rio se cadastra
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER SET search_path = public
AS $$
BEGIN
  -- Criar perfil
  INSERT INTO public.profiles (id, name, photo_url)
  VALUES (new.id, new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'avatar_url');
  
  -- Inicializar tokens (10 MatchCoins iniciais)
  INSERT INTO public.tokens (user_id, balance)
  VALUES (new.id, 10);
  
  RETURN new;
END;
$$;

-- Trigger para novos usuÃ¡rios
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();


-- Function para atualizar contador de likes
CREATE OR REPLACE FUNCTION public.update_likes_count()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  IF (TG_OP = 'INSERT') THEN
    UPDATE public.community_posts
    SET likes_count = likes_count + 1
    WHERE id = new.post_id;
  ELSIF (TG_OP = 'DELETE') THEN
    UPDATE public.community_posts
    SET likes_count = likes_count - 1
    WHERE id = old.post_id;
  END IF;
  RETURN null;
END;
$$;

-- Trigger para likes
DROP TRIGGER IF EXISTS on_like_change ON public.community_likes;
CREATE TRIGGER on_like_change
  AFTER INSERT OR DELETE ON public.community_likes
  FOR EACH ROW EXECUTE PROCEDURE public.update_likes_count();


-- Function para atualizar contador de comentÃ¡rios
CREATE OR REPLACE FUNCTION public.update_comments_count()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  IF (TG_OP = 'INSERT') THEN
    UPDATE public.community_posts
    SET comments_count = comments_count + 1
    WHERE id = new.post_id;
  ELSIF (TG_OP = 'DELETE') THEN
    UPDATE public.community_posts
    SET comments_count = comments_count - 1
    WHERE id = old.post_id;
  END IF;
  RETURN null;
END;
$$;

-- Trigger para comentÃ¡rios
DROP TRIGGER IF EXISTS on_comment_change ON public.community_comments;
CREATE TRIGGER on_comment_change
  AFTER INSERT OR DELETE ON public.community_comments
  FOR EACH ROW EXECUTE PROCEDURE public.update_comments_count();


-- Function para atualizar filled_slots automaticamente
CREATE OR REPLACE FUNCTION public.update_filled_slots()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER SET search_path = public
AS $$
BEGIN
  IF (TG_OP = 'INSERT') THEN
    UPDATE public.matches
    SET filled_slots = filled_slots + 1
    WHERE id = new.match_id;
  ELSIF (TG_OP = 'DELETE') THEN
    UPDATE public.matches
    SET filled_slots = filled_slots - 1
    WHERE id = old.match_id;
  END IF;
  RETURN null;
END;
$$;

-- Trigger para participantes
DROP TRIGGER IF EXISTS on_participant_change ON public.match_participants;
CREATE TRIGGER on_participant_change
  AFTER INSERT OR DELETE ON public.match_participants
  FOR EACH ROW EXECUTE PROCEDURE public.update_filled_slots();


-- Function para atualizar updated_at em amizades
CREATE OR REPLACE FUNCTION public.update_updated_at_column()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$;

-- Trigger para amizades
DROP TRIGGER IF EXISTS update_friendships_updated_at ON public.friendships;
CREATE TRIGGER update_friendships_updated_at
    BEFORE UPDATE ON public.friendships
    FOR EACH ROW
    EXECUTE FUNCTION public.update_updated_at_column();


-- ========================================
-- 16. FUNCTIONS RPC
-- ========================================

-- Function: Adicionar tokens
CREATE OR REPLACE FUNCTION public.add_tokens(p_user_id uuid, amount int)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  INSERT INTO public.tokens (user_id, balance)
  VALUES (p_user_id, amount)
  ON CONFLICT (user_id)
  DO UPDATE SET balance = tokens.balance + amount, updated_at = now();
END;
$$;


-- Function: Gastar tokens (genÃ©rico)
CREATE OR REPLACE FUNCTION public.spend_tokens(p_user_id uuid, amount int)
RETURNS text
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  current_bal int;
BEGIN
  SELECT balance INTO current_bal FROM public.tokens WHERE user_id = p_user_id;
  
  IF current_bal IS NULL THEN
    RETURN 'INSUFFICIENT_FUNDS'; 
  END IF;

  IF current_bal >= amount THEN
    UPDATE public.tokens
    SET balance = balance - amount, updated_at = now()
    WHERE user_id = p_user_id;
    RETURN 'OK';
  ELSE
    RETURN 'INSUFFICIENT_FUNDS';
  END IF;
END;
$$;


-- Function: Criar partida com tokens (custo: 3 tokens)
CREATE OR REPLACE FUNCTION public.create_match_with_tokens(
  p_name text,
  p_sport text,
  p_location text,
  p_lat real,
  p_lng real,
  p_date timestamp with time zone,
  p_slots int,
  p_rules text,
  p_is_private boolean,
  p_invite_code text,
  p_team_id BIGINT DEFAULT NULL
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_user_id uuid;
  v_balance int;
  v_new_match_id bigint;
  v_match_data jsonb;
BEGIN
  v_user_id := auth.uid();
  IF v_user_id IS NULL THEN
    RAISE EXCEPTION 'NOT_AUTHENTICATED';
  END IF;

  -- Verificar saldo
  SELECT balance INTO v_balance FROM public.tokens WHERE user_id = v_user_id;
  IF v_balance IS NULL OR v_balance < 3 THEN
    RAISE EXCEPTION 'INSUFFICIENT_FUNDS';
  END IF;

  -- 1. Deduzir tokens
  UPDATE public.tokens SET balance = balance - 3 WHERE user_id = v_user_id;

  -- 2. Criar partida
  INSERT INTO public.matches (
    created_by, name, sport, location, lat, lng, date, slots, rules, is_private, invite_code, team_id
  ) VALUES (
    v_user_id, p_name, p_sport, p_location, p_lat, p_lng, p_date, p_slots, p_rules, p_is_private, p_invite_code, p_team_id
  ) RETURNING id INTO v_new_match_id;

  -- 3. Retornar dados da partida criada
  SELECT to_jsonb(m) INTO v_match_data FROM public.matches m WHERE id = v_new_match_id;
  
  RETURN v_match_data;
END;
$$;


-- Function: Entrar na partida (custo: 1 token)
CREATE OR REPLACE FUNCTION public.join_match_with_token(p_match_id bigint)
RETURNS text
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_user_id uuid;
  v_balance int;
  v_match record;
  v_is_participant boolean;
BEGIN
  v_user_id := auth.uid();
  IF v_user_id IS NULL THEN
    RETURN 'NOT_AUTHENTICATED';
  END IF;

  -- Verificar status da partida
  SELECT * INTO v_match FROM public.matches WHERE id = p_match_id;
  IF v_match IS NULL THEN
    RETURN 'MATCH_NOT_FOUND';
  END IF;
  
  IF v_match.status != 'Convocando' THEN
    RETURN 'MATCH_CLOSED';
  END IF;
  
  IF v_match.filled_slots >= v_match.slots THEN
    RETURN 'MATCH_FULL';
  END IF;

  -- Verificar se jÃ¡ estÃ¡ na partida
  SELECT EXISTS(SELECT 1 FROM public.match_participants WHERE match_id = p_match_id AND user_id = v_user_id) INTO v_is_participant;
  IF v_is_participant THEN
    RETURN 'ALREADY_IN';
  END IF;

  -- Verificar saldo de tokens
  SELECT balance INTO v_balance FROM public.tokens WHERE user_id = v_user_id;
  IF v_balance IS NULL OR v_balance < 1 THEN
    RETURN 'NO_TOKENS';
  END IF;

  -- EXECUTAR TRANSAÃ‡ÃƒO
  -- 1. Deduzir token
  UPDATE public.tokens SET balance = balance - 1 WHERE user_id = v_user_id;
  
  -- 2. Adicionar participante
  INSERT INTO public.match_participants (match_id, user_id) VALUES (p_match_id, v_user_id);

  RETURN 'OK';
END;
$$;


-- Function: Sair da partida (reembolso: 1 token)
CREATE OR REPLACE FUNCTION public.leave_match_with_refund(p_match_id bigint)
RETURNS text
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_user_id uuid;
  v_deleted_count int;
BEGIN
  v_user_id := auth.uid();
  IF v_user_id IS NULL THEN
    RETURN 'NOT_AUTHENTICATED';
  END IF;

  -- Deletar participante e verificar se houve exclusÃ£o
  WITH deleted AS (
    DELETE FROM public.match_participants 
    WHERE match_id = p_match_id AND user_id = v_user_id
    RETURNING *
  )
  SELECT count(*) INTO v_deleted_count FROM deleted;

  IF v_deleted_count = 0 THEN
    RETURN 'NOT_IN_MATCH';
  END IF;

  -- Reembolsar token
  UPDATE public.tokens SET balance = balance + 1 WHERE user_id = v_user_id;

  RETURN 'OK';
END;
$$;


-- Function: Cancelar partida
CREATE OR REPLACE FUNCTION public.cancel_match(p_match_id bigint, p_user_id uuid, p_reason text)
RETURNS text
LANGUAGE plpgsql
SECURITY DEFINER SET search_path = public
AS $$
BEGIN
  UPDATE public.matches
  SET
    status = 'Cancelado',
    cancellation_reason = p_reason
  WHERE
    id = p_match_id AND
    created_by = p_user_id;
  
  IF NOT FOUND THEN
    RAISE EXCEPTION 'User is not the creator of the match or match not found.';
  END IF;
  
  RETURN 'Partida cancelada com sucesso!';
END;
$$;


-- Function: Boost na partida (custo: 2 tokens)
CREATE OR REPLACE FUNCTION public.boost_match(p_match_id bigint, p_user_id uuid)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    v_balance int;
    v_boost_until timestamptz := now() + interval '12 hour';
    v_match record;
BEGIN
    -- Verificar saldo do usuÃ¡rio
    SELECT balance INTO v_balance FROM public.tokens WHERE user_id = p_user_id;
    IF v_balance IS NULL OR v_balance < 2 THEN
        RETURN jsonb_build_object('status', 'INSUFFICIENT_FUNDS');
    END IF;

    -- Atualizar a partida
    UPDATE public.matches
    SET boost_score = COALESCE(boost_score, 0) + 1,
        is_boosted = true,
        boost_until = v_boost_until
    WHERE id = p_match_id
    RETURNING * INTO v_match;

    IF NOT FOUND THEN
        RETURN jsonb_build_object('status', 'MATCH_NOT_FOUND');
    END IF;

    -- Deduzir tokens
    UPDATE public.tokens
    SET balance = balance - 2,
        updated_at = now()
    WHERE user_id = p_user_id;

    -- Retornar partida atualizada
    RETURN jsonb_build_object(
        'status', 'OK',
        'match', jsonb_build_object(
            'id', v_match.id,
            'boost_score', v_match.boost_score,
            'is_boosted', v_match.is_boosted,
            'boost_until', v_match.boost_until,
            'date', v_match.date,
            'name', v_match.name,
            'sport', v_match.sport,
            'location', v_match.location,
            'slots', v_match.slots,
            'filled_slots', v_match.filled_slots,
            'status', v_match.status
        )
    );
END;
$$;


-- Function: Finalizar partidas expiradas
CREATE OR REPLACE FUNCTION public.finalize_expired_matches()
RETURNS TABLE(finalized_count INTEGER)
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    count_updated INTEGER;
BEGIN
    UPDATE public.matches
    SET status = 'Finalizada'
    WHERE date < NOW()
      AND status NOT IN ('Finalizada', 'Cancelado');
    
    GET DIAGNOSTICS count_updated = ROW_COUNT;
    
    RETURN QUERY SELECT count_updated;
END;
$$;


-- Function: Helper para incrementar contador
CREATE OR REPLACE FUNCTION public.increment_counter(row_id uuid, col_name text)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
END;
$$;


-- ========================================
-- 17. GRANT DE PERMISSÃ•ES
-- ========================================

GRANT EXECUTE ON FUNCTION public.join_match_with_token(bigint) TO authenticated;
GRANT EXECUTE ON FUNCTION public.leave_match_with_refund(bigint) TO authenticated;
GRANT EXECUTE ON FUNCTION public.boost_match(bigint, uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.finalize_expired_matches() TO authenticated, anon, service_role;


-- ========================================
-- 18. STORAGE SETUP
-- ========================================

-- Criar bucket 'team-logos' se nÃ£o existir
INSERT INTO storage.buckets (id, name, public)
VALUES ('team-logos', 'team-logos', true)
ON CONFLICT (id) DO NOTHING;

-- PolÃ­ticas de Storage
CREATE POLICY "Logos de time sÃ£o pÃºblicos"
ON storage.objects FOR SELECT
USING ( bucket_id = 'team-logos' );

CREATE POLICY "UsuÃ¡rios autenticados podem fazer upload de logos"
ON storage.objects FOR INSERT
WITH CHECK (
  bucket_id = 'team-logos'
  AND auth.role() = 'authenticated'
);

CREATE POLICY "UsuÃ¡rios autenticados podem atualizar logos"
ON storage.objects FOR UPDATE
USING ( bucket_id = 'team-logos' AND auth.role() = 'authenticated' );

CREATE POLICY "UsuÃ¡rios autenticados podem deletar logos"
ON storage.objects FOR DELETE
USING ( bucket_id = 'team-logos' AND auth.role() = 'authenticated' );


-- ========================================
-- 19. FINALIZAÃ‡ÃƒO IMEDIATA
-- ========================================

-- Finalizar partidas expiradas existentes
SELECT public.finalize_expired_matches();


-- ========================================
-- FIM DA MIGRAÃ‡ÃƒO
-- ========================================

