
-- Tabela de Times
CREATE TABLE IF NOT EXISTS public.teams (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_by UUID NOT NULL REFERENCES auth.users(id),
    name TEXT NOT NULL,
    description TEXT,
    logo_url TEXT,
    invite_code TEXT UNIQUE DEFAULT encode(gen_random_bytes(6), 'hex'),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Tabela de Membros do Time
CREATE TABLE IF NOT EXISTS public.team_members (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    team_id BIGINT NOT NULL REFERENCES public.teams(id) ON DELETE CASCADE,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    status TEXT NOT NULL CHECK (status IN ('pending', 'approved', 'rejected')),
    role TEXT NOT NULL DEFAULT 'member' CHECK (role IN ('admin', 'member')),
    joined_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    UNIQUE(team_id, user_id)
);

-- RLS: Teams
ALTER TABLE public.teams ENABLE ROW LEVEL SECURITY;

-- Leitura pública de times (necessário para ver quem criou ou para páginas de time)
CREATE POLICY "Times são visíveis para todos" ON public.teams
    FOR SELECT USING (true);

-- Criação apenas para usuários autenticados
CREATE POLICY "Usuários autenticados podem criar times" ON public.teams
    FOR INSERT WITH CHECK (auth.uid() = created_by);

-- Atualização apenas pelo criador
CREATE POLICY "Apenas criador pode editar time" ON public.teams
    FOR UPDATE USING (auth.uid() = created_by);

-- Exclusão apenas pelo criador
CREATE POLICY "Apenas criador pode deletar time" ON public.teams
    FOR DELETE USING (auth.uid() = created_by);


-- RLS: Team Members
ALTER TABLE public.team_members ENABLE ROW LEVEL SECURITY;

-- Leitura de membros visível para todos (para ver quem participa do time)
CREATE POLICY "Membros de time são visíveis para todos" ON public.team_members
    FOR SELECT USING (true);

-- Inserção: Usuário pode pedir para entrar (status pending) OU Admin pode adicionar (autoupdate via trigger/function se necessário, mas por enquanto insert simples)
-- Vamos permitir que qualquer user autenticado insira um registro SE O USER_ID for ele mesmo (pedir para entrar)
CREATE POLICY "Usuários podem solicitar entrada" ON public.team_members
    FOR INSERT WITH CHECK (auth.uid() = user_id);

-- Atualização: Apenas ADMIN do time pode atualizar status (aprovar/rejeitar/promover)
-- OU o próprio usuário pode sair (cancelar pedido ou sair do time)
CREATE POLICY "Admins podem atualizar membros" ON public.team_members
    FOR UPDATE USING (
        EXISTS (
            SELECT 1 FROM public.teams
            WHERE id = team_members.team_id AND created_by = auth.uid()
        )
        OR
        EXISTS (
            SELECT 1 FROM public.team_members AS tm
            WHERE tm.team_id = team_members.team_id
            AND tm.user_id = auth.uid()
            AND tm.role = 'admin'
            AND tm.status = 'approved'
        )
    );

-- Delete: Admins podem remover, ou o próprio usuário pode sair
CREATE POLICY "Admins removem ou usuario sai" ON public.team_members
    FOR DELETE USING (
        user_id = auth.uid() -- O próprio usuário saindo
        OR
        EXISTS ( -- Admin removendo
            SELECT 1 FROM public.teams
            WHERE id = team_members.team_id AND created_by = auth.uid()
        )
        OR
        EXISTS ( -- Outro admin removendo
            SELECT 1 FROM public.team_members AS tm
            WHERE tm.team_id = team_members.team_id
            AND tm.user_id = auth.uid()
            AND tm.role = 'admin'
            AND tm.status = 'approved'
        )
    );
